### ISSUE TITLE
listRaster incorrectly returning some layers

### ISSUE THREAD

**Issue by Danpfeffer** [malaria-atlas-project/malariaAtlas#39]
e.g. vivax PR and incidence rasters are not available to download but are visible to listRaster.

**Comment by Danpfeffer** [comment]
@shk313 @timcdlucas 

I added a branch and a first-attempt mini-fix to this in 63daeaf3b8807dfecea1c68dc3e4ae15e5ef9be3, @shk313 would you mind having a look at this and see that what i've done works? 

Cheers!

**Comment by jcanoortega** [comment]
Trying to retrieve falciparum and vivax PR and incidence data but not working. Got an error message related with server. Neither is it working when using extractRaster() function to get the pixel values for coordinates. I check out with other layers and seem to only affect these that I mention above.

Cheers!

**Comment by timcdlucas** [comment]
Hi @jcanoortega. Thanks for getting in touch.

These new global incidence and PR layers (Pv and Pf) are currently not for download until the papers are published I believe. 63daeaf fixes it so that they no longer show up in listRaster. But ultimately we're just waiting for the data to be fully released.

Sorry about that.

**Comment by jcanoortega** [comment]
Hi @timcdlucas. Thanks for letting me know. 
Nevertheless, the rasters are being displayed as images through the interactive malaria map tool, so that this means it would go live soon?
Thanks.

**Comment by timcdlucas** [comment]
Yes, they are displayed. There is a note that says they are not for download but I'm aware this isn't very clear!

But yes, I believe it will be soon. In the order of weeks hopefully. I'll comment in this thread again and tag you when they are live if you like. 

Thanks again for your interest!

**Comment by timcdlucas** [comment]
Hi @jcanoortega. The new layers are now up and working. Hope that's everything sorted and thanks for the interest. Please let us know if you find anymore issues.

One thing to note is that the new global rasters for PfPR is named "Plasmodium falciparum PR2 - 10" while the older, Africa only rasters are called "Plasmodium falciparum PR2-10". 

I'm going to close this issue now as I think that is everything working.
