### ISSUE TITLE
Shape data not downloadable

### ISSUE THREAD

**Issue by haohanchen** [malaria-atlas-project/malariaAtlas#53]
Hi there,

Thank you for the great package! I just got some error message when I tried to download some shape files. Could you help?

Input: 
`listData(datatype = "shape")`

Error message:

`[1] "Error in file(file, \"rt\") : \n  cannot open the connection to 'https://malariaatlas.org/geoserver/Explorer/ows?service=wfs&version=2.0.0&request=GetFeature&outputFormat=csv&TypeName=mapadmin_0_2018&PROPERTYNAME=iso,admn_level,name_0,id_0,type_0,source'\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in file(file, "rt"): cannot open the connection to 'https://malariaatlas.org/geoserver/Explorer/ows?service=wfs&version=2.0.0&request=GetFeature&outputFormat=csv&TypeName=mapadmin_0_2018&PROPERTYNAME=iso,admn_level,name_0,id_0,type_0,source'>`

Input: 

`MDG_shp <- getShp(ISO = "MDG", admin_level = c("admin0", "admin1"))`

Error message: 

`Error in file(file, "rt") : 
  cannot open the connection to 'https://malariaatlas.org/geoserver/Explorer/ows?service=wfs&version=2.0.0&request=GetFeature&outputFormat=csv&TypeName=mapadmin_0_2018&PROPERTYNAME=iso,admn_level,name_0,id_0,type_0,source'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://malariaatlas.org/geoserver/Explorer/ows?service=wfs&version=2.0.0&request=GetFeature&outputFormat=csv&TypeName=mapadmin_0_2018&PROPERTYNAME=iso,admn_level,name_0,id_0,type_0,source': HTTP status was '400 Bad Request'
Error in file(file, "rt") : 
  cannot open the connection to 'https://malariaatlas.org/geoserver/Explorer/ows?service=wfs&version=2.0.0&request=GetFeature&outputFormat=csv&TypeName=mapadmin_0_2018&PROPERTYNAME=iso,admn_level,name_0,id_0,type_0,source'
Error in file(file, "rt") : 
  cannot open the connection to 'https://malariaatlas.org/geoserver/Explorer/ows?service=wfs&version=2.0.0&request=GetFeature&outputFormat=csv&TypeName=mapadmin_0_2018&PROPERTYNAME=iso,admn_level,name_0,id_0,type_0,source'`

**Comment by timcdlucas** [comment]
Hi,

Thanks for getting in touch. I'll have a look. It's worth trying again in a day or so just in case it was a temporary server issue.

Tim

**Comment by haohanchen** [comment]
Hi Tim,

Thanks for the quick response! I'll try a few more times today and tomorrow and let you know how it goes.

Best,
Haohan

**Comment by timcdlucas** [comment]
These lines are working for me. My guess it was a temporary server outage. Please let me know if everything is working for you now.

**Comment by haohanchen** [comment]
Thank you, Tim! I just ran the script again. It works now. Really appreciate your follow-up and thank you again for the great package!

Best,
Haohan

**Comment by timcdlucas** [comment]
No problem. Glad it's working!
