### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [malaria-atlas-project/malariaAtlas#59]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

And **disaggregation** too, please!

**Comment by timcdlucas** [comment]
Thanks for the heads up. 

I had seen your recent post and opened an issue for disaggregation.
https://github.com/aknandi/disaggregation/issues/70

Do you have any timelines for the depreciation? Obviously we should just sort everything out on our side asap, but as I'm sure you can imagine carving out time is sometimes tricky.

@joemap we never quite formalised the handover and I'm still the CRAN maintainer. This seems like the appropriate time to get it all handed over properly. Do you have people and time? As always happy to help as needed.

**Comment by rsbivand** [comment]
A sketch of a timeline is given in the recent blog, link above. Roughly June 2023, to get summer schools and the northern hemisphere teaching year onto the new footing. Probably closing out in October 2023, which means that packages that were then still trying to use the retiring packages that will be archived in October would have to scramble to avoid being archived themselves.

**Comment by timcdlucas** [comment]
Thank you very much. I'll make sure to get stuff sorted in time to avoid a scramble.

**Comment by joemap** [comment]
> @joemap we never quite formalised the handover and I'm still the CRAN maintainer. This seems like the appropriate time to get it all handed over properly. Do you have people and time? As always happy to help as needed.

Thanks Tim! We greatly appreciate all you've done, and for so long after departing MAP. So you'll perhaps be relieved to hear Camilo is planning for our team to put a lot more focus into R in the new year; and we have a great new member of staff who has recently started and will initially be focussing specifically on R packages. So, we'll be able to complete the remaining handover with a plan to start more active R development after the relevant people are back from an extended holiday break - this will be in the latter half of January.

Thanks again and happy holidays!

**Comment by rsbivand** [comment]
Please see update on https://github.com/aknandi/disaggregation/issues/70.

malariaAtlas imports 'rgdal' using `rgdal::readOGR` as found by `pkgapi`, not in NAMESPACE, in R/getShp.R line 313. Since `raster` is used, usinng `terra::vect` and coercion to sp (method in `raster`) should be feasible. Please fix best by June, latest October 2023.

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.

**Comment by timcdlucas** [comment]
Hi @joemap @mauricio-tki 

Just thought I'd check whether there's some movement on this. As I'm still formally the maintainer of malariaAtlas on CRAN, we'll have to do a few emails and things to transfer ownership over to you before you can update with the new spatial packages.

I'm in the process of updating another package, so happy to help out. Absolutely happy to get on a call with the new staff member to give them an overview of the package and what sorts of things will need to be replaced. But really hoping to avoid having to do it all myself.

Tim

**Comment by rsbivand** [comment]
Thaks for refreshing this, it now needs action soon.

**Comment by cavargasru** [comment]
@timcdlucas thanks for this, indeed. Quick update is we are working on a new version of the package that integrates better with the new architecture of our data platform. My expectation is to have a release of it at the end of September to meet this October deadline.

**Comment by timcdlucas** [comment]
Hi @cavargasru. That sounds good. If you get to a useful intermediate stage, it might be worth submitting that to CRAN so that we can deal with the maintainorship handover early. Might be easier to do that in a separate submission with plenty of time before this October deadline if that makes sense.

Tim

**Comment by cavargasru** [comment]
Yes it makes sense @timcdlucas. Let me get back to you on that. Thanks again

**Comment by rsbivand** [comment]
@timcdlucas Just a polite reminder that less than three months remain until `rgdal` is archived on CRAN and out of active service.

**Comment by mauricio-tki** [comment]
Thanks @rsbivand and @timcdlucas for the help and reminders. I've updated the package to remove `rgdal`, `raster` and `sp` (current HEAD and tagged as `1.2.0`). AFAICT the only thing remaining is the optional dependency `rdhs` which still depends on `rgdal`.
  
Working with @timcdlucas to transfer ownership and get the package on CRAN now.
