### ISSUE TITLE
`getShp` returns error when passed the 'ALL' parameter

### ISSUE THREAD

**Issue by rjzupkoii** [malaria-atlas-project/malariaAtlas#65]
When using the version 1.5.1 of the interface installed via `remotes::install_github("malaria-atlas-project/malariaAtlas")` the `getShp`  function returns the following errors:

```R
> shp <- malariaAtlas::getShp(ISO = "ALL", version = '202206')
Error in malariaAtlas::getShp(ISO = "ALL", version = "202206") : 
  One or more ISO codes are wrong
> shp <- malariaAtlas::getShp(country = "ALL", version = '202206')
Error in malariaAtlas::getShp(country = "ALL", version = "202206") : 
  One or more country names are wrong
```

Based upon [the documentation](https://rdrr.io/github/malaria-atlas-project/malariaAtlas/man/getShp.html) hosted on rddr.io, I would expect to be able download all of the shapefiles using either of these commands.

**Comment by mauricio-tki** [comment]
Thanks for filing this issue @rjzupkoii, that should indeed be possible.

I've just pushed a fix to master, and will probably do a new release on CRAN some time next week.
