### ISSUE TITLE
No connection to MAP geoserver

### ISSUE THREAD

**Issue by cruzmamo** [malaria-atlas-project/malariaAtlas#67]
Hi everyone,

I have been experiencing issues connecting to MAP.

`> library(malariaAtlas)`
`> getPR(country = 'Senegal', species = 'Pf')`

Gives me:

`Loading ISO 19139 XML schemas...
Loading ISO 19115 codelists...
Error in names(namespaces) <- rep("", length(namespaces)) : 
  Failed to connect to MAP geoserver. Please try again later. If this error keeps occurring please send us an email at data.malariaatlas.org@telethonkids.org.au`

I tried downloading the data from different machines that have different R versions (4.4.1 and 4.3.3), but the error remains the same. I also removed and re-installed the 'malariaAtlas' package. 

Has anyone else experienced this error?

**Comment by joemap** [comment]
Hi @cruzmamo, thanks for flagging this. There was an interruption to our GeoServer being able to provide WFS services, but these have now been restored. Apologies for any inconvenience caused. Let us know if you are still experiencing any issues.
